services:
  - type: web
    name: fintrack-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: fintrack-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET  
        generateValue: true
    healthCheckPath: /health

  - type: web
    name: fintrack-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: fintrack-frontend
          property: host
      - key: NEXT_PUBLIC_GRAPHQL_URL
        value: https://fintrack-backend.onrender.com/graphql
      - key: NEXT_PUBLIC_API_URL
        value: https://fintrack-backend.onrender.com

databases:
  - name: fintrack-postgres
    databaseName: fintrack
    user: fintrack